server:
  port: 10002

spring:
  application:
    name: Piggy-Auth
  # MySQL 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/piggy_data?useSSL=false&serverTimezone=UTC
    username: root
    password: ${mysql.password:Dengyuxin666}
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 驼峰命名
  global-config:
    db-config:
      id-type: auto